name: 'Init environment variables'
description: 'Init environment variables'


inputs:
  env-json-base64:
    description: 'base64 json'
    required: true


runs:
  using: "composite"
  steps: 
    - run: |
        echo ${{ inputs.env-json-base64 }} | base64 --decode > data.json
        CONTAINERREGISTRY=$(jq -r '.REGISTRY' data.json)
        REGISTRY_SUBPATH=$(jq -r '.REGISTRY_SUBPATH' data.json)
        COMPANY=$(jq -r '.COMPANY' data.json)
        KUBEBOT=$(jq -r '.KUBEBOT' data.json)
        echo "::set-env name=CONTAINERREGISTRY::$CONTAINERREGISTRY"
        echo "::set-env name=REGISTRY_SUBPATH::$REGISTRY_SUBPATH"
        echo "::set-env name=COMPANY::$COMPANY"
        echo "::set-env name=KUBEBOT::$KUBEBOT"
        echo $CONTAINERREGISTRY
        echo $REGISTRY_SUBPATH
        echo $COMPANY
        echo $KUBEBOT
      shell: bash

