name: 'Init environment variables'
description: 'Init environment variables'


inputs:
  env-json-base64:
    description: 'base64 json'
    required: true


runs:
  using: "composite"
  steps: 
    - name: Check Hash
      run: |
        head_hash=$(git rev-parse HEAD)
        current_hash=${GITHUB_SHA}
        echo "HEAD hash=$head_hash"
        echo "ACTION hash=$current_hash"
        if [ $head_hash = $current_hash ]; then
           echo "hash check ok!"
        else
           echo "Looks like miss commits, aborting .."
           exit 1
        fi    
      shell: bash

    - name: Init Envs
      run: |
        data=$(echo ${{ inputs.env-json-base64 }} | base64 --decode)
        CONTAINERREGISTRY=$(echo $data | jq -r '.REGISTRY')
        REPOSITORY=$(echo $data | jq -r '.REPOSITORY')
        COMPANY=$(echo $data | jq -r '.COMPANY')
        KUBEBOT=$(echo $data | jq -r '.KUBEBOT')
        CLIENTID=$(echo $data | jq -r '.CLIENTID')
        CLIENTSECRET=$(echo $data | jq -r '.CLIENTSECRET')
        TENANT=$(echo $data | jq -r '.TENANT')
        echo "CONTAINERREGISTRY=$CONTAINERREGISTRY" >> $GITHUB_ENV
        echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
        echo "COMPANY=$COMPANY" >> $GITHUB_ENV
        echo "KUBEBOT=$KUBEBOT" >> $GITHUB_ENV
        
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $GITHUBSHA | cut -c1-6)
        echo "TAG=$TAG" >> $GITHUB_ENV

        echo "init environment variables ok!"

        az login --service-principal -u $CLIENTID -p $CLIENTSECRET --tenant $TENANT
        az acr login -n $CONTAINERREGISTRY
        echo "ACR login successfully!"
      shell: bash

