name: 'Init environment variables'
description: 'Init environment variables'


inputs:
  env-json-base64:
    description: 'base64 json'
    required: true


runs:
  using: "composite"
  steps: 
    - name: Check Hash
      run: |
        head_hash=$(git rev-parse HEAD)
        current_hash=${GITHUB_SHA}
        echo "HEAD hash=$head_hash"
        echo "ACTION hash=$current_hash"
        if [ $head_hash = $current_hash ]; then
           echo "hash check ok!"
        else
           echo "Looks like miss commits, aborting .."
           exit 1
        fi    
      shell: bash

    - name: Init Envs
      run: |
        echo ${{ inputs.env-json-base64 }} | base64 --decode > data.json
        CONTAINERREGISTRY=$(jq -r '.REGISTRY' data.json)
        REPOSITORY=$(jq -r '.REPOSITORY' data.json)
        COMPANY=$(jq -r '.COMPANY' data.json)
        KUBEBOT=$(jq -r '.KUBEBOT' data.json)
        echo "CONTAINERREGISTRY=$CONTAINERREGISTRY" >> $GITHUB_ENV
        echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
        echo "COMPANY=$COMPANY" >> $GITHUB_ENV
        echo "KUBEBOT=$KUBEBOT" >> $GITHUB_ENV
        
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $GITHUBSHA | cut -c1-6)
        echo "TAG=$TAG" >> $GITHUB_ENV

        echo "init environment variables ok!"
      shell: bash

